### ISSUE TITLE
invalid Discord `#orbit-support` link on Orbit chain deployment portal

### ISSUE THREAD

**Issue by leeederek** [OffchainLabs/orbit-deployment-ui#81]
Hey, noticed that the Orbit chain deployment portal has an invalid discord invite link to #orbit-support. I believe the issue is [here](https://github.com/OffchainLabs/orbit-deployment-ui/blob/main/app/page.tsx#L60). 

As a user, I'd expect the link to take me to the Arbitrum Discord at minimum and in the best case, directly to the #orbit-support channel.

To reproduce:
1. Visit: https://orbit.arbitrum.io/

2. Click on "Get Support
<img width="500" alt="image" src="https://github.com/OffchainLabs/orbit-deployment-ui/assets/103802618/edee07ec-8810-4b80-bc6b-99a18ecdb046">

3. See invalid invite link: https://discord.com/invite/KsewXePB
<img width="500" alt="image" src="https://github.com/OffchainLabs/orbit-deployment-ui/assets/103802618/64f0890b-527d-44fa-bcb9-54388fcf434f">

**Comment by fionnachan** [comment]
Thanks for the report @leeederek 
In the meantime, please use https://discord.gg/arbitrum

**Comment by fionnachan** [comment]
closed by #82
